/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.sistema.dono;

import views.sistema.pessoa.*;
import dao.lugar.DAOEndereco;
import dao.usuarios.DAODono;
import modelos.usuarios.Pessoa;
import dao.usuarios.DAOPessoa;
import dao.usuarios.DAOPessoa;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import modelos.lugar.Endereco;
import modelos.usuarios.Dono;
import modelos.usuarios.Pessoa;
import sistema.Conexao;
/**
 *
 * @author Yara
 */
public class consultarDadosPessoaisDono extends javax.swing.JFrame {
    private Dono dono;
    /**
     * Creates new form ConsultarDadosEmprego
     */
    public consultarDadosPessoaisDono(String cpf) {
        if(cpf != null){
            this.dono = new DAODono().readOneDono(cpf);
            initComponents();
            iniciaTabela();
            populaComboEndereco();
        }else{
            initComponents();
        }
    }
        
    public void iniciaTabela(){
        Dono resultado = new DAODono().readOneDono(dono.getCpf());

           DefaultTableModel testetabela = (DefaultTableModel) tabelaDados.getModel();
           Object[] colunas = {"Nome","Senha","Login"};
           final Object[] entrada = new Object[4];
           entrada[0] = resultado.getNome(); 
           entrada[1] = resultado.getSenha();
           entrada[2] = resultado.getLogin();
           if(testetabela.getRowCount() > 0){
               testetabela.removeRow(testetabela.getRowCount()-1);
           }
           testetabela.setColumnIdentifiers(colunas);
           testetabela.addRow(entrada);
           tabelaDados.setModel(testetabela);
            
    }
    
    private void populaComboEndereco(){
        Conexao conexao = new Conexao();
        conexao.conect();
        ArrayList<Endereco> enderecos = new DAOEndereco().readAll();
        
        if(!enderecos.isEmpty()){
            
            comboboxEndereco.removeAllItems();
            
            for (Endereco endereco : enderecos) {
                comboboxEndereco.addItem(endereco.getRua()+","+endereco.getId());                
            }
            
        }else{
            comboboxEndereco.removeAllItems();
            comboboxEndereco.addItem("Nenhum endereço cadastrado");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaDados = new javax.swing.JTable();
        backButton = new javax.swing.JButton();
        nameAlterButton = new javax.swing.JButton();
        nameTextField = new javax.swing.JTextField();
        adressAlterButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        loginTextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        comboboxEndereco = new javax.swing.JComboBox<>();
        criarEndereco = new javax.swing.JButton();
        loginAlterButton = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        passwordAlterButton = new javax.swing.JButton();
        passwordTextField = new javax.swing.JTextField();
        errorMessage = new javax.swing.JLabel();

        jScrollPane2.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Poppins", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Consultar Dados - Dono");

        tabelaDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "nome", "login", "senha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabelaDados.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tabelaDados);
        tabelaDados.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        backButton.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        backButton.setText("Voltar");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        nameAlterButton.setText("Alterar Nome");
        nameAlterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameAlterButtonActionPerformed(evt);
            }
        });

        nameTextField.setToolTipText("");
        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });

        adressAlterButton.setLabel("Alterar Endereço");
        adressAlterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adressAlterButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel3.setText("Nome:");

        loginTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginTextFieldActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel15.setText("Login:");

        jLabel6.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel6.setText("Endereço:");

        comboboxEndereco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nenhum endereço cadastrado" }));
        comboboxEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxEnderecoActionPerformed(evt);
            }
        });

        criarEndereco.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        criarEndereco.setText("Criar Novo Endereço");
        criarEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarEnderecoActionPerformed(evt);
            }
        });

        loginAlterButton.setLabel("Alterar Login");
        loginAlterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginAlterButtonActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel16.setText("Senha");

        passwordAlterButton.setLabel("Alterar Senha");
        passwordAlterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordAlterButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(backButton)
                        .addGap(123, 123, 123)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(loginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(comboboxEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameAlterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(loginAlterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(331, 331, 331)
                                .addComponent(adressAlterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(errorMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel16)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(passwordAlterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(192, 192, 192)
                                .addComponent(criarEndereco))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(backButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(nameAlterButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboboxEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adressAlterButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(loginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginAlterButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordAlterButton)
                    .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(criarEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        dono.mostrarMenu();
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void adressAlterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adressAlterButtonActionPerformed
        
    }//GEN-LAST:event_adressAlterButtonActionPerformed

    private void loginTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginTextFieldActionPerformed

    private void criarEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarEnderecoActionPerformed
        dono.criarNovoEndereco("Consultar",-1);
        this.dispose();
    }//GEN-LAST:event_criarEnderecoActionPerformed

    private void loginAlterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginAlterButtonActionPerformed
        boolean error = false;
        String login = loginTextField.getText();
        
        if(login.length() == 0){
            errorMessage.setText("O campo login não pode estar vazio");
            error = true;
        }
        
        if(!error){
            errorMessage.setText("");
        }
        
        if(error){
            return;
        }
        
        DAODono daoDono = new DAODono();
        daoDono.updateDono("login", this.dono.getCpf(), login);
        
        this.dono = daoDono.readOneDono(this.dono.getCpf());
        
        iniciaTabela();
    }//GEN-LAST:event_loginAlterButtonActionPerformed

    private void nameAlterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameAlterButtonActionPerformed
        boolean error = false;
        String nome = nameTextField.getText();
        
        if(nome.length() == 0){
            errorMessage.setText("O campo nome não pode estar vazio");
            error = true;
        }
        
        if(!error){
            errorMessage.setText("");
        }
        
        if(error){
            return;
        }
        
        DAODono daoDono = new DAODono();
        daoDono.updateDono("nome", this.dono.getCpf(), nome);
        
        this.dono = daoDono.readOneDono(this.dono.getCpf());
        
        iniciaTabela();
    }//GEN-LAST:event_nameAlterButtonActionPerformed

    private void passwordAlterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordAlterButtonActionPerformed
        boolean error = false;
        String password = passwordTextField.getText();
        
        if(password.length() == 0){
            errorMessage.setText("O campo senha não pode estar vazio");
            error = true;
        }
        
        if(!error){
            errorMessage.setText("");
        }
        
        if(error){
            return;
        }
        
        DAODono daoDono = new DAODono();
        daoDono.updateDono("senha", this.dono.getCpf(), password);
        
        this.dono = daoDono.readOneDono(this.dono.getCpf());
        
        iniciaTabela();
    }//GEN-LAST:event_passwordAlterButtonActionPerformed

    private void comboboxEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxEnderecoActionPerformed
        
    }//GEN-LAST:event_comboboxEnderecoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(consultarDadosPessoaisDono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(consultarDadosPessoaisDono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(consultarDadosPessoaisDono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(consultarDadosPessoaisDono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new consultarDadosPessoaisDono(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adressAlterButton;
    private javax.swing.JButton backButton;
    private javax.swing.JComboBox<String> comboboxEndereco;
    private javax.swing.JButton criarEndereco;
    private javax.swing.JLabel errorMessage;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton loginAlterButton;
    private javax.swing.JTextField loginTextField;
    private javax.swing.JButton nameAlterButton;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton passwordAlterButton;
    private javax.swing.JTextField passwordTextField;
    private javax.swing.JTable tabelaDados;
    // End of variables declaration//GEN-END:variables
}
