/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.sistema.dono;

import javax.swing.JFrame;

import dao.usuarios.DAODono;
import dao.empresa.DAOEmpresa;
import dao.usuarios.DAOFuncionario;
import javax.swing.table.DefaultTableModel;
import modelos.usuarios.Dono;
import modelos.usuarios.Funcionario;
import modelos.usuarios.Pessoa;
import modelos.empresa.Empresa;
import views.sistema.categoria.CadastrarCategoria;
import views.sistema.dono.MenuDono;

/**
 *
 * @author sarah
 */
public class MenuDono_AdmEmpresa extends javax.swing.JFrame {
    private Dono dono;
    private Empresa empresa;
    /**
     * Creates new form AlterarDadosEmpresaDono
     */
    public MenuDono_AdmEmpresa(String cpf) {
        if(cpf != null){
            this.dono = new DAODono().readOneDono(cpf);
            initComponents();
            iniciaTabela();
        }else{
            initComponents();
        }
    }
    
    public void iniciaTabela(){

        this.empresa = new DAOEmpresa().readOnEmpresa(dono.getCpf(), "cpf");

        DefaultTableModel testetabela = (DefaultTableModel) tabelaDados.getModel();
        Object[] colunas = {"nome","cnpj","orcamento"};
        final Object[] entrada = new Object[4];
        entrada[0] = empresa.getNome(); 
        entrada[1] = empresa.getCnpj();
        entrada[2] = empresa.getOrcamento();
        if(testetabela.getRowCount() > 0){
            testetabela.removeRow(testetabela.getRowCount()-1);
        }
        testetabela.setColumnIdentifiers(colunas);
        testetabela.addRow(entrada);
        tabelaDados.setModel(testetabela);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nomeAlterButton = new javax.swing.JButton();
        orcamentoAlterButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaDados = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        nomeEmpresaTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        orcamentoTextField = new javax.swing.JTextField();
        clearButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        deleteCheckBox = new javax.swing.JCheckBox();
        criarCatButton = new javax.swing.JButton();
        admSetoresButton = new javax.swing.JButton();
        admDiretoresButton = new javax.swing.JButton();
        errorMessage = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Poppins", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Administrar Empresa");

        nomeAlterButton.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        nomeAlterButton.setText("Alterar Nome da Empresa");
        nomeAlterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeAlterButtonActionPerformed(evt);
            }
        });

        orcamentoAlterButton.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        orcamentoAlterButton.setText("Alterar Orçamento da Empresa");
        orcamentoAlterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orcamentoAlterButtonActionPerformed(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        backButton.setText("Voltar");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        tabelaDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome da Empresa", "CNPJ", "Orçamento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaDados);
        if (tabelaDados.getColumnModel().getColumnCount() > 0) {
            tabelaDados.getColumnModel().getColumn(0).setResizable(false);
            tabelaDados.getColumnModel().getColumn(1).setResizable(false);
            tabelaDados.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel2.setText("Nome da Empresa:");

        nomeEmpresaTextField.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel3.setText("Orçamento:");

        orcamentoTextField.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        orcamentoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orcamentoTextFieldActionPerformed(evt);
            }
        });

        clearButton.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        clearButton.setText("Limpar");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        deleteButton.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        deleteButton.setText("Excluir Empresa");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        deleteCheckBox.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        deleteCheckBox.setText("Confirmar exclusão ");
        deleteCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCheckBoxActionPerformed(evt);
            }
        });

        criarCatButton.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        criarCatButton.setText("Criar Categoria");
        criarCatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarCatButtonActionPerformed(evt);
            }
        });

        admSetoresButton.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        admSetoresButton.setText("Administrar Setores");
        admSetoresButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admSetoresButtonActionPerformed(evt);
            }
        });

        admDiretoresButton.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        admDiretoresButton.setText("Administrar Diretores");
        admDiretoresButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admDiretoresButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Adicionar Empresa");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(backButton)
                            .addGap(197, 197, 197)
                            .addComponent(jLabel1))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(errorMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nomeEmpresaTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                                    .addComponent(orcamentoTextField))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(orcamentoAlterButton, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                                    .addComponent(nomeAlterButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(admDiretoresButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(admSetoresButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(criarCatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(269, 269, 269)))
                                .addComponent(deleteCheckBox)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(0, 49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nomeEmpresaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeAlterButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(orcamentoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(orcamentoAlterButton))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(clearButton)
                        .addComponent(deleteButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteCheckBox)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(admSetoresButton)
                        .addComponent(criarCatButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(admDiretoresButton)
                    .addComponent(jButton1))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeAlterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeAlterButtonActionPerformed
        boolean error = false;
        String nome = nomeEmpresaTextField.getText();
        
        if(nome.length() == 0){
            errorMessage.setText("O campo nome da empresa não pode estar vazio");
            error = true;
        }
        
        if(!error){
            errorMessage.setText("");
        }
        
        if(error){
            return;
        }
        
        DAOEmpresa daoEmpresa = new DAOEmpresa();
        String cnpj = daoEmpresa.readOnEmpresa(dono.getCpf(), "cpf").getCnpj();
        daoEmpresa.updateEmpresa("nome", cnpj, nome);
        
        //empresa = daoEmpresa.readOnEmpresa(this.empresa.getCnpj());
        
        iniciaTabela();
    }//GEN-LAST:event_nomeAlterButtonActionPerformed

    private void criarCatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarCatButtonActionPerformed
        CadastrarCategoria menuCadCategoria = new CadastrarCategoria( dono.getCpf());
        menuCadCategoria.setVisible(true);
        menuCadCategoria.pack();
        menuCadCategoria.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_criarCatButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        dono.mostrarMenu();

        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void admSetoresButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admSetoresButtonActionPerformed
        this.empresa = new DAOEmpresa().readOnEmpresa(this.dono.getCpf(), "cpf");
        dono.administrarSetores(empresa.getCnpj());
        
        this.dispose();
    }//GEN-LAST:event_admSetoresButtonActionPerformed

    private void admDiretoresButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admDiretoresButtonActionPerformed
        dono.administrarDiretores();
        this.dispose();
    }//GEN-LAST:event_admDiretoresButtonActionPerformed

    private void orcamentoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orcamentoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orcamentoTextFieldActionPerformed

    private void orcamentoAlterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orcamentoAlterButtonActionPerformed
        boolean error = false;
        String orcamento = orcamentoTextField.getText();
        
        if(orcamento.length() == 0){
            errorMessage.setText("O campo orçamento da empresa não pode estar vazio");
            error = true;
        }
        
        if(!error){
            errorMessage.setText("");
        }
        
        if(error){
            return;
        }
        
        DAOEmpresa daoEmpresa = new DAOEmpresa();
        daoEmpresa.updateEmpresa("orcamento", this.empresa.getCnpj(), orcamento);
        
        //this.empresa = daoEmpresa.readOnEmpresa(this.empresa.getCnpj());
        
        iniciaTabela();
    }//GEN-LAST:event_orcamentoAlterButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        nomeEmpresaTextField.setText("");
        orcamentoTextField.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void deleteCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteCheckBoxActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        boolean errorCheckbox = false, errorFild = false;

        if(deleteCheckBox.isSelected() != true){
            errorMessage.setText("Para deletar a empresa, você deve marcar o campo confirmar exclusão.");
            errorCheckbox = true;
        }
        if(!errorCheckbox){
            errorMessage.setText("");
        }
        
        if(errorCheckbox){
            return;
        }
        
        DefaultTableModel testetabela = (DefaultTableModel) tabelaDados.getModel();
        if(tabelaDados.getSelectedRowCount() == 1){
            testetabela.removeRow(tabelaDados.getSelectedRow());
            new DAOEmpresa().deleteEmpresa(this.empresa.getCnpj());
            
        } else {
            if(tabelaDados.getRowCount() == 0){
                errorMessage.setText("Tabela vazia.");
            } else {
                errorMessage.setText("É preciso selecionar a linha que deseja deletar.");
            }
        }
        
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Empresa empresa = new DAOEmpresa().readOnEmpresa(dono.getCpf(), "cpf");
        if(empresa != null){
            errorMessage.setText("Você não pode ter mais de uma empresa.");
            return;
        } else{

        } 
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuDono_AdmEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuDono_AdmEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuDono_AdmEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuDono_AdmEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuDono_AdmEmpresa(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton admDiretoresButton;
    private javax.swing.JButton admSetoresButton;
    private javax.swing.JButton backButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton criarCatButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JCheckBox deleteCheckBox;
    private javax.swing.JLabel errorMessage;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nomeAlterButton;
    private javax.swing.JTextField nomeEmpresaTextField;
    private javax.swing.JButton orcamentoAlterButton;
    private javax.swing.JTextField orcamentoTextField;
    private javax.swing.JTable tabelaDados;
    // End of variables declaration//GEN-END:variables
}
